files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    content_segmentation: '0'
    translatable_elements:
      - /resources/string/
