/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca_datacollection;

import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.List;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author liza
 */
public class Welcome extends javax.swing.JFrame {
    
    static ServerSocket ss;
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dout;
    int count = 0;


    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

        String finaluser;
        String data_path = "C:\\Users\\ljivnani\\Desktop\\Ca_home_data\\";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Task2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextPane();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        task4 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_gen_pass = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        btn_nextPass = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        task8 = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        task7 = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta4 = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        task5 = new javax.swing.JFrame();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta5 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        task6 = new javax.swing.JFrame();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta6 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        task10 = new javax.swing.JFrame();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta10 = new javax.swing.JTextArea();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Task1 = new javax.swing.JFrame();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        pp = new javax.swing.JTextField();
        up = new javax.swing.JTextField();
        pu = new javax.swing.JTextField();
        bp = new javax.swing.JTextField();
        uu = new javax.swing.JTextField();
        wp = new javax.swing.JTextField();
        bu = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();
        wu = new javax.swing.JTextField();
        su = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        task_8 = new javax.swing.JFrame();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Task3 = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn_g = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        Task2.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        Task2.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 211);

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setOpaque(true);
        Task2.getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 80, 2210, 90);

        jLabel4.setBackground(new java.awt.Color(51, 84, 34));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        Task2.getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 0, 2210, 80);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<HTML> Use the TextBox Below to type the given handwritten essay.  </HTML>");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Task2.getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 1130, 70);

        jButton21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton21.setText("Submit");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton21);
        jButton21.setBounds(1040, 910, 340, 70);

        jButton22.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton22.setText("Restart Task");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton22);
        jButton22.setBounds(50, 910, 340, 70);

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Bold");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton6);
        jButton6.setBounds(50, 340, 140, 60);

        ta1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ta1.setAutoscrolls(false);
        jScrollPane8.setViewportView(ta1);

        Task2.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(50, 400, 1330, 500);

        jButton7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton7.setText("Italic");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton7);
        jButton7.setBounds(190, 340, 130, 60);

        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setText("Remove Style");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton9);
        jButton9.setBounds(470, 340, 140, 60);

        jButton19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton19.setText("<html>\n<u>Underline</u>\n</html>");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Task2.getContentPane().add(jButton19);
        jButton19.setBounds(320, 340, 150, 60);

        task4.addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                task4WindowStateChanged(evt);
            }
        });
        task4.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task4.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 200, 211);

        jLabel10.setBackground(new java.awt.Color(51, 84, 34));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        task4.getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 0, 2210, 80);

        jLabel11.setBackground(new java.awt.Color(255, 255, 153));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setOpaque(true);
        task4.getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 80, 2210, 90);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("In each textbox below, enter the provided password five times");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task4.getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 230, 1110, 70);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel13.setText("Password:");
        task4.getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 410, 320, 60);

        txt_gen_pass.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt_gen_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_gen_pass.setText("GmxPV3L");
        txt_gen_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task4.getContentPane().add(txt_gen_pass);
        txt_gen_pass.setBounds(60, 490, 350, 80);

        txt2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt2.setToolTipText("");
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt2KeyPressed(evt);
            }
        });
        task4.getContentPane().add(txt2);
        txt2.setBounds(580, 440, 470, 90);

        txt3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt3.setToolTipText("");
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt3KeyPressed(evt);
            }
        });
        task4.getContentPane().add(txt3);
        txt3.setBounds(580, 570, 470, 90);

        txt4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt4.setToolTipText("");
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt4KeyPressed(evt);
            }
        });
        task4.getContentPane().add(txt4);
        txt4.setBounds(580, 810, 470, 90);

        txt1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt1.setToolTipText("");
        txt1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txt1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });
        task4.getContentPane().add(txt1);
        txt1.setBounds(580, 320, 470, 90);

        btn_nextPass.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn_nextPass.setText("Next Password");
        btn_nextPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextPassActionPerformed(evt);
            }
        });
        task4.getContentPane().add(btn_nextPass);
        btn_nextPass.setBounds(1180, 910, 340, 70);

        jButton20.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton20.setText("Restart Task");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        task4.getContentPane().add(jButton20);
        jButton20.setBounds(70, 920, 340, 70);

        txt5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt5.setToolTipText("");
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt5KeyPressed(evt);
            }
        });
        task4.getContentPane().add(txt5);
        txt5.setBounds(580, 690, 470, 90);

        task8.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task8.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 200, 211);

        jLabel16.setBackground(new java.awt.Color(51, 84, 34));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);
        task8.getContentPane().add(jLabel16);
        jLabel16.setBounds(210, 0, 2210, 80);

        jLabel17.setBackground(new java.awt.Color(255, 255, 153));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel17.setOpaque(true);
        task8.getContentPane().add(jLabel17);
        jLabel17.setBounds(210, 80, 2210, 90);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel18.setText("<HTML>   You will now watch a Short video. Using the textbox below  describe what you think is happennnig in the video and how the video makes you feel.    </HTML>");
        jLabel18.setAutoscrolls(true);
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task8.getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 230, 1830, 90);

        ta3.setColumns(20);
        ta3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ta3.setRows(5);
        ta3.setText("\n\n\n");
        jScrollPane2.setViewportView(ta3);

        task8.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 390, 1700, 430);

        jButton17.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton17.setText("Submit");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        task8.getContentPane().add(jButton17);
        jButton17.setBounds(1080, 910, 340, 70);

        jButton18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton18.setText("Restart Task");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        task8.getContentPane().add(jButton18);
        jButton18.setBounds(70, 910, 340, 70);

        task7.getContentPane().setLayout(null);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task7.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 200, 211);

        jLabel29.setBackground(new java.awt.Color(51, 84, 34));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setOpaque(true);
        task7.getContentPane().add(jLabel29);
        jLabel29.setBounds(210, 0, 2210, 80);

        jLabel30.setBackground(new java.awt.Color(255, 255, 153));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel30.setOpaque(true);
        task7.getContentPane().add(jLabel30);
        jLabel30.setBounds(210, 80, 2210, 90);

        ta4.setColumns(20);
        ta4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ta4.setRows(5);
        ta4.setText("\n\n\n");
        jScrollPane4.setViewportView(ta4);

        task7.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(50, 400, 1700, 430);

        jButton15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton15.setText("Submit");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        task7.getContentPane().add(jButton15);
        jButton15.setBounds(1410, 910, 340, 70);

        jButton16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton16.setText("Restart Task");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        task7.getContentPane().add(jButton16);
        jButton16.setBounds(70, 910, 340, 70);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel20.setText("<HTML>   You will now watch a Short video. Using the textbox below  describe what you think is happennnig in the video and how the video makes you feel.    </HTML>");
        jLabel20.setAutoscrolls(true);
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task7.getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 230, 1830, 90);

        task5.getContentPane().setLayout(null);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task5.getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 200, 211);

        jLabel33.setBackground(new java.awt.Color(51, 84, 34));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.setOpaque(true);
        task5.getContentPane().add(jLabel33);
        jLabel33.setBounds(210, 0, 2210, 80);

        jLabel34.setBackground(new java.awt.Color(255, 255, 153));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel34.setOpaque(true);
        task5.getContentPane().add(jLabel34);
        jLabel34.setBounds(210, 80, 2210, 90);

        ta5.setColumns(20);
        ta5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ta5.setRows(5);
        ta5.setText("\n\n\n");
        jScrollPane5.setViewportView(ta5);

        task5.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(50, 400, 1700, 430);

        jButton13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton13.setText("Submit");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        task5.getContentPane().add(jButton13);
        jButton13.setBounds(1410, 910, 340, 70);

        jButton14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton14.setText("Restart Task");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        task5.getContentPane().add(jButton14);
        jButton14.setBounds(70, 910, 340, 70);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel19.setText("<HTML>   You will now watch a Short video. Using the textbox below  describe what you think is happennnig in the video and how the video makes you feel.    </HTML>");
        jLabel19.setAutoscrolls(true);
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task5.getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 230, 1830, 90);

        task6.getContentPane().setLayout(null);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task6.getContentPane().add(jLabel36);
        jLabel36.setBounds(0, 0, 200, 211);

        jLabel37.setBackground(new java.awt.Color(51, 84, 34));
        jLabel37.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.setOpaque(true);
        task6.getContentPane().add(jLabel37);
        jLabel37.setBounds(210, 0, 2210, 80);

        jLabel38.setBackground(new java.awt.Color(255, 255, 153));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel38.setOpaque(true);
        task6.getContentPane().add(jLabel38);
        jLabel38.setBounds(210, 80, 2210, 90);

        ta6.setColumns(20);
        ta6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ta6.setRows(5);
        ta6.setText("\n\n\n");
        jScrollPane6.setViewportView(ta6);

        task6.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(50, 400, 1700, 430);

        jButton8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        task6.getContentPane().add(jButton8);
        jButton8.setBounds(1410, 910, 340, 70);

        jButton12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton12.setText("Restart Task");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        task6.getContentPane().add(jButton12);
        jButton12.setBounds(70, 910, 340, 70);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel21.setText("<HTML>   You will now watch a Short video. Using the textbox below  describe what you think is happennnig in the video and how the video makes you feel.    </HTML>");
        jLabel21.setAutoscrolls(true);
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task6.getContentPane().add(jLabel21);
        jLabel21.setBounds(60, 230, 1830, 90);

        task10.getContentPane().setLayout(null);

        jLabel40.setBackground(new java.awt.Color(255, 255, 153));
        jLabel40.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel40.setOpaque(true);
        task10.getContentPane().add(jLabel40);
        jLabel40.setBounds(210, 80, 2210, 90);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task10.getContentPane().add(jLabel41);
        jLabel41.setBounds(0, 0, 200, 211);

        jLabel43.setBackground(new java.awt.Color(51, 84, 34));
        jLabel43.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel43.setOpaque(true);
        task10.getContentPane().add(jLabel43);
        jLabel43.setBounds(210, 0, 2210, 80);

        ta10.setColumns(20);
        ta10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ta10.setRows(5);
        ta10.setText("\n\n\n");
        jScrollPane7.setViewportView(ta10);

        task10.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(50, 400, 1700, 430);

        jButton23.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton23.setText("Restart Task");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        task10.getContentPane().add(jButton23);
        jButton23.setBounds(70, 910, 340, 70);

        jButton24.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton24.setText("Submit\n");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        task10.getContentPane().add(jButton24);
        jButton24.setBounds(1410, 910, 340, 70);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel27.setText("<HTML>   You will now watch a Short video. Using the textbox below  describe what you think is happennnig in the video and how the video makes you feel.    </HTML>");
        jLabel27.setAutoscrolls(true);
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task10.getContentPane().add(jLabel27);
        jLabel27.setBounds(60, 230, 1830, 90);

        Task1.getContentPane().setLayout(null);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        Task1.getContentPane().add(jLabel44);
        jLabel44.setBounds(0, 0, 200, 211);

        jLabel45.setBackground(new java.awt.Color(51, 84, 34));
        jLabel45.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel45.setOpaque(true);
        Task1.getContentPane().add(jLabel45);
        jLabel45.setBounds(210, 0, 2210, 80);

        jLabel46.setBackground(new java.awt.Color(255, 255, 153));
        jLabel46.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel46.setOpaque(true);
        Task1.getContentPane().add(jLabel46);
        jLabel46.setBounds(210, 80, 2210, 90);

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Password");
        Task1.getContentPane().add(jLabel47);
        jLabel47.setBounds(1330, 320, 330, 70);

        jButton10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton10.setText("Restart Task");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(jButton10);
        jButton10.setBounds(500, 940, 340, 70);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Enter username and password combinations as if you are setting up different types of accounts.");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Task1.getContentPane().add(jLabel49);
        jLabel49.setBounds(60, 230, 1670, 70);

        jLabel48.setBackground(new java.awt.Color(204, 255, 255));
        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel48.setText("<HTML>\na <b> utility </b> account \n\n\n</HTML?>");
        jLabel48.setText("<HTML>\na <b> chat </b> account to communicate with friends \n\n\n</HTML?>");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel48.setOpaque(true);
        Task1.getContentPane().add(jLabel48);
        jLabel48.setBounds(70, 510, 340, 60);

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Username");
        Task1.getContentPane().add(jLabel51);
        jLabel51.setBounds(720, 330, 330, 70);

        jLabel52.setBackground(new java.awt.Color(204, 255, 204));
        jLabel52.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel52.setText("<HTML>\na <b> banking </b> account \n\n\n</HTML?>");
        jLabel52.setText("<HTML>\na <b> bank or money savings </b> account \n\n\n</HTML?>");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel52.setOpaque(true);
        Task1.getContentPane().add(jLabel52);
        jLabel52.setBounds(70, 610, 340, 60);

        jLabel53.setBackground(new java.awt.Color(255, 204, 204));
        jLabel53.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel53.setText("<HTML>\na <b> work-hosted </b> account \n\n\n</HTML?>");
        jLabel53.setText("<HTML>\na <b> gaming </b> account \n\n\n</HTML?>");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel53.setOpaque(true);
        Task1.getContentPane().add(jLabel53);
        jLabel53.setBounds(70, 710, 340, 60);

        jLabel54.setBackground(new java.awt.Color(255, 255, 204));
        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("<HTML>\na <b> school </b> account \n\n\n</HTML?>");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel54.setOpaque(true);
        Task1.getContentPane().add(jLabel54);
        jLabel54.setBounds(70, 810, 340, 60);

        jLabel56.setBackground(new java.awt.Color(204, 204, 204));
        jLabel56.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("<HTML>\na <b> streaming service </b> account like YouTube \n\n\n</HTML?>");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel56.setOpaque(true);
        Task1.getContentPane().add(jLabel56);
        jLabel56.setBounds(70, 420, 340, 60);

        pp.setBackground(new java.awt.Color(204, 204, 204));
        pp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(pp);
        pp.setBounds(1350, 420, 530, 60);

        up.setBackground(new java.awt.Color(204, 255, 255));
        up.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        up.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(up);
        up.setBounds(1350, 510, 530, 60);

        pu.setBackground(new java.awt.Color(204, 204, 204));
        pu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(pu);
        pu.setBounds(730, 410, 530, 60);

        bp.setBackground(new java.awt.Color(204, 255, 204));
        bp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(bp);
        bp.setBounds(1350, 600, 530, 60);

        uu.setBackground(new java.awt.Color(204, 255, 255));
        uu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        uu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uuActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(uu);
        uu.setBounds(730, 500, 530, 60);

        wp.setBackground(new java.awt.Color(255, 204, 204));
        wp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        wp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(wp);
        wp.setBounds(1350, 700, 530, 60);

        bu.setBackground(new java.awt.Color(204, 255, 204));
        bu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(bu);
        bu.setBounds(730, 600, 530, 60);

        sp.setBackground(new java.awt.Color(255, 255, 204));
        sp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(sp);
        sp.setBounds(1350, 810, 530, 60);

        wu.setBackground(new java.awt.Color(255, 204, 204));
        wu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        wu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wuActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(wu);
        wu.setBounds(730, 700, 530, 60);

        su.setBackground(new java.awt.Color(255, 255, 204));
        su.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        su.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        su.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(su);
        su.setBounds(730, 810, 530, 60);

        jButton11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton11.setText("Submit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Task1.getContentPane().add(jButton11);
        jButton11.setBounds(880, 940, 340, 70);

        task_8.getContentPane().setLayout(null);

        jLabel22.setBackground(new java.awt.Color(255, 255, 153));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel22.setOpaque(true);
        task_8.getContentPane().add(jLabel22);
        jLabel22.setBounds(210, 80, 2210, 90);

        jLabel23.setBackground(new java.awt.Color(51, 84, 34));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setOpaque(true);
        task_8.getContentPane().add(jLabel23);
        jLabel23.setBounds(210, 0, 2210, 80);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        task_8.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 200, 211);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel26.setText(" You will now chat with a member of the research team in the textbox below");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task_8.getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 260, 1220, 70);

        msg_area.setEditable(false);
        msg_area.setColumns(20);
        msg_area.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        msg_area.setRows(5);
        jScrollPane3.setViewportView(msg_area);

        task_8.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 360, 1220, 400);

        msg_text.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        task_8.getContentPane().add(msg_text);
        msg_text.setBounds(30, 790, 920, 80);

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        task_8.getContentPane().add(jButton2);
        jButton2.setBounds(990, 800, 250, 70);

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Restart Task");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        task_8.getContentPane().add(jButton3);
        jButton3.setBounds(30, 920, 250, 70);

        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        task_8.getContentPane().add(jButton4);
        jButton4.setBounds(1610, 920, 250, 70);

        Task3.getContentPane().setLayout(null);

        jLabel14.setBackground(new java.awt.Color(51, 84, 34));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        Task3.getContentPane().add(jLabel14);
        jLabel14.setBounds(210, 0, 2210, 80);

        jLabel28.setBackground(new java.awt.Color(255, 255, 153));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel28.setOpaque(true);
        Task3.getContentPane().add(jLabel28);
        jLabel28.setBounds(210, 80, 2210, 90);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        Task3.getContentPane().add(jLabel31);
        jLabel31.setBounds(0, 0, 200, 211);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("<HTML> Use the options below to do search a receipe of your choice </HTML>");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Task3.getContentPane().add(jLabel35);
        jLabel35.setBounds(60, 230, 1110, 70);

        btn_1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn_1.setText("Search on Tasty.co");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        Task3.getContentPane().add(btn_1);
        btn_1.setBounds(710, 330, 410, 90);

        btn2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn2.setText("Click here to proceed to next task");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        Task3.getContentPane().add(btn2);
        btn2.setBounds(220, 820, 760, 90);

        btn_g.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn_g.setText("Search on Google");
        btn_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gActionPerformed(evt);
            }
        });
        Task3.getContentPane().add(btn_g);
        btn_g.setBounds(120, 390, 410, 90);

        btn3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn3.setText("Search on Epicurious");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        Task3.getContentPane().add(btn3);
        btn3.setBounds(710, 530, 410, 90);

        btn_2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn_2.setText("Search on Food Network");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        Task3.getContentPane().add(btn_2);
        btn_2.setBounds(710, 430, 410, 90);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel55.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca_datacollection/usf.png"))); // NOI18N
        getContentPane().add(jLabel55);
        jLabel55.setBounds(0, 0, 200, 211);

        jLabel57.setBackground(new java.awt.Color(51, 84, 34));
        jLabel57.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel57.setOpaque(true);
        getContentPane().add(jLabel57);
        jLabel57.setBounds(210, 0, 2210, 80);

        jLabel58.setBackground(new java.awt.Color(255, 255, 153));
        jLabel58.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel58.setOpaque(true);
        getContentPane().add(jLabel58);
        jLabel58.setBounds(210, 80, 2210, 90);

        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setText("Proceed to tasks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 260, 960, 150);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       try{

       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_6.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(ta6.getText());
       doc.createParagraph().createRun();
       doc.write(outStream);
       task7.setExtendedState(task7.getExtendedState() | JFrame.MAXIMIZED_BOTH);
       task7.setVisible(true);
   }catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        bu.setText("");
        bp.setText("");
        
        uu.setText("");
        up.setText("");
        
        pu.setText("");
        pp.setText("");
        
        wu.setText("");
        wp.setText("");
        
        su.setText("");
        sp.setText("");
        
       

    }//GEN-LAST:event_jButton10ActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed

    private void puActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puActionPerformed

    private void bpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpActionPerformed

    private void uuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uuActionPerformed

    private void wpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpActionPerformed

    private void buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spActionPerformed

    private void wuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wuActionPerformed

    private void suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try{

    
       String pass = "personal  "+ pu.getText()+"\n"+pp.getText()+"\n\n"+
                     "utility   "+uu.getText()+"\n"+up.getText()+"\n\n"+
                    "work   "  +wu.getText()+"\n"+wp.getText()+"\n\n"+
                    "banking    "+bu.getText()+"\n"+bp.getText()+"\n\n"+
                    "School     "+su.getText()+"\n"+sp.getText()+"\n\n";
       
       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_9.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(pass);
       doc.createParagraph().createRun();
       doc.write(outStream);
       Task2.setExtendedState(Task2.getExtendedState() | JFrame.MAXIMIZED_BOTH);
       Task2.setVisible(true);
       
       

}catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }          
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
ta6.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 try{

       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_5.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(ta5.getText());
       doc.createParagraph().createRun();
       doc.write(outStream);
       task6.setExtendedState(task6.getExtendedState() | JFrame.MAXIMIZED_BOTH);

       task6.setVisible(true);
   }catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
ta5.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{

       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_4.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(ta4.getText());
       doc.createParagraph().createRun();
       doc.write(outStream);
       task8.setExtendedState(task8.getExtendedState() | JFrame.MAXIMIZED_BOTH);

       task8.setVisible(true);
   }catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
ta4.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 try{

       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_3.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(ta3.getText());
       doc.createParagraph().createRun();
       doc.write(outStream);
      System.out.println("createdocument.docx written successully");
      JOptionPane.showMessageDialog(this, "Please go to the couch to perform your last task on the mobile device ");
      System.exit(0);
 
   }catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
ta3.setText("");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btn_nextPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextPassActionPerformed
        ArrayList<String> pass_list = new ArrayList<String>();
        pass_list.add("GmxPV3L");
        pass_list.add("Nv5PHS!8kP8");
        pass_list.add("jxK&5sDpwfE+U");
        
        
        System.out.print(count);
             
        String pass = pass_list.get(this.count);
            
            if (txt1.getText().equals(pass) && txt2.getText().equals(pass) && txt3.getText().equals(pass) && txt4.getText().equals(pass) && txt5.getText().equals(pass))
                {
                            count += 1;
                
                            if(this.count >= 3)
                                {
                                     System.out.print(">3");

                                        System.out.print(""+count);
                                        JOptionPane.showMessageDialog(this, "You may now go the couch and use the mobile phone/device on the central  table to perform the next two tasks");
                                        
                                        System.exit(0);
                                        
                                        //task5.setExtendedState(task5.getExtendedState() | JFrame.MAXIMIZED_BOTH);

                                       // task5.setVisible(true);

                                }
                
                            else if(count == 2)
                            {
                                txt_gen_pass.setText(pass_list.get(this.count));
                                btn_nextPass.setText("Submit");
                                txt1.setText("");
                                txt2.setText("");
                                txt3.setText("");
                                txt4.setText("");
                                txt5.setText("");
                            }
                            
                            else
                            {
                                
                                txt1.setText("");
                                txt2.setText("");
                                txt3.setText("");
                                txt4.setText("");
                                txt5.setText("");
                                txt_gen_pass.setText(pass_list.get(this.count));
                            }
                                   
                
                            
                            
                            
                            
                }
            
                else
                {   
                    
                if(!txt1.getText().equals(pass))
                        {
                            txt1.setText("");
                        }
                
                 if(!txt2.getText().equals(pass))
                        {
                            txt2.setText("");
                        }
                
                  if(!txt3.getText().equals(pass))
                        {
                            txt3.setText("");
                        }
                
                   if(!txt4.getText().equals(pass))
                        {
                            txt4.setText("");
                        }
                   
                    if(!txt5.getText().equals(pass))
                        {
                            txt5.setText("");
                        }
                
                
                
                    JOptionPane.showMessageDialog(this, "Incorrect Entry. Please make sure that all the passwords match.");
                    
                }
            
            

        
        
       /* txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");*/
        
       
        
       
        
        
       
    }//GEN-LAST:event_btn_nextPassActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        
        
        
        
    }//GEN-LAST:event_jButton20ActionPerformed

    
    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
ta1.setText("");

    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
       try{

       FileOutputStream outStream = new FileOutputStream(data_path+"\\task_10.docx");
       XWPFDocument doc;
       doc = new XWPFDocument();
       XWPFParagraph paraTit=doc.createParagraph();
       paraTit.setAlignment(ParagraphAlignment.CENTER);
       XWPFRun paraTitRun=paraTit.createRun();
       paraTitRun.setBold(true);
       paraTitRun.setText(ta10.getText());
       doc.createParagraph().createRun();
       doc.write(outStream);
       System.exit(0);
       }catch (HeadlessException | IOException e){
       JOptionPane.showMessageDialog(null, e);
   }  
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/*try
{
   Class.forName("java.sql.Driver");

   String Database="jdbc:mysql://localhost:3306/ca_datacollection";

   Connection conn =(Connection)DriverManager.getConnection(Database,"root","unlocksql");
   


   Statement stmt=conn.createStatement();
   
   String u = txtuser.getText();
   String p = new String(txtpass.getPassword());
   
   
     String query="select * from login where user = '"+u+"'";
     ResultSet rs=stmt.executeQuery(query); 
   
   
   if (rs.next())
   {
       String u2 = rs.getString("user");
       String p2 = rs.getString("pass");
       if(p.equals(p2))
       {
           finaluser=u2;
           
           File file = new File(data_path+finaluser);
           if(!file.exists())
           {
                 file.mkdir();
               
           }
          Task2.setExtendedState(Task2.getExtendedState() | JFrame.MAXIMIZED_BOTH);

           Task2.setVisible(true);
           
       }
       
    
       else
       {
           JOptionPane.showMessageDialog(this,"Invalid password!!","Error",JOptionPane.ERROR_MESSAGE);
       }
    }
   else
   {
       JOptionPane.showMessageDialog(this,"No Such User Exists","Error",JOptionPane.ERROR_MESSAGE);
   }
   
   }     


catch (ClassNotFoundException |SQLException|HeadlessException ex) 

{
                    
                    JOptionPane.showMessageDialog(this,"Error in connecting !!","Error",JOptionPane.ERROR_MESSAGE);

    } */

 Task1.setExtendedState(Task1.getExtendedState() | JFrame.MAXIMIZED_BOTH);

 Task1.setVisible(true);

                                       

  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
        String msg="";
        msg=msg_text.getText();
        
        String cur_text = msg_area.getText();
        cur_text += "\n";
        cur_text += "participant: "+ msg;
        
        msg_area.setText(cur_text);
        dout.writeUTF(msg);
        msg_text.setText("");
        }
        catch(Exception e)
        {
        //handle the exception here
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       msg_area.setText("");
       msg_text.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        try {
            FileOutputStream outStream = new FileOutputStream(data_path+"\\task_chat.docx");
            XWPFDocument doc;
            doc = new XWPFDocument();
            XWPFParagraph paraTit=doc.createParagraph();
            paraTit.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun paraTitRun=paraTit.createRun();
            paraTitRun.setBold(true);
            paraTitRun.setText(msg_area.getText());
            doc.createParagraph().createRun();
            doc.write(outStream);

        }
        
    catch (FileNotFoundException ex) {
        Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
    }   
    catch (IOException ex)
    {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void task4WindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_task4WindowStateChanged
     

    }//GEN-LAST:event_task4WindowStateChanged

    private void txt1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1CaretPositionChanged

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
       txt1.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
       txt1.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");

    }//GEN-LAST:event_txt1KeyPressed

    private void txt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyPressed
 txt2.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
 txt2.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");


    }//GEN-LAST:event_txt2KeyPressed

    private void txt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyPressed
      txt3.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
      txt3.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");


    }//GEN-LAST:event_txt3KeyPressed

    private void txt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyPressed
     txt5.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
     txt5.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");

    }//GEN-LAST:event_txt5KeyPressed

    private void txt4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyPressed
       txt4.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
       txt4.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");

    }//GEN-LAST:event_txt4KeyPressed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
      
        try
        {
            String url = "https://tasty.co/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            btn2.setEnabled(true);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        ta1.setText("");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        try{

            FileOutputStream outStream = new FileOutputStream(data_path+"\\task_1.docx");
            XWPFDocument doc;
            doc = new XWPFDocument();
            XWPFParagraph paraTit=doc.createParagraph();
            paraTit.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun paraTitRun=paraTit.createRun();
            paraTitRun.setBold(true);
            paraTitRun.setText(ta1.getText());
            doc.createParagraph().createRun();
            doc.write(outStream);
            Task3.setExtendedState(Task3.getExtendedState() | JFrame.MAXIMIZED_BOTH);

            Task3.setVisible(true);
        }
        catch (HeadlessException | IOException e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton21ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
     task4.setExtendedState(task4.getExtendedState() | JFrame.MAXIMIZED_BOTH);

            task4.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        String s1 = ta1.getText();
        
        int mark = ta1.getCaret().getMark();
        int dot = ta1.getCaret().getDot();
       
       StyledDocument style_obj = (StyledDocument) ta1.getDocument();
       
      try {
                int length = dot - mark;
                String s = style_obj.getText(mark, length);
                
                //style_obj.remove(mark, length);
                
                //style_obj.insertString(mark, s,
                        //style_obj.getStyle("bold"));
                
                Style style = style_obj.addStyle("Bold", null);
                StyleConstants.setBold(style, true);
                
                style_obj.setCharacterAttributes(mark, length, style, false);
                

            } 
      catch (BadLocationException e) {
                e.printStackTrace();
            }
       
      
              
       //  JOptionPane.showMessageDialog(this, s );
        
       
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String s1 = ta1.getText();
        
        int mark = ta1.getCaret().getMark();
        int dot = ta1.getCaret().getDot();
       
       StyledDocument style_obj = (StyledDocument) ta1.getDocument();
       
      try {
                int length = dot - mark;
                String s = style_obj.getText(mark, length);
                
                //style_obj.remove(mark, length);
                
                //style_obj.insertString(mark, s,
                        //style_obj.getStyle("bold"));
                
                Style style = style_obj.addStyle("Italic", null);
                StyleConstants.setItalic(style, true);
                
                style_obj.setCharacterAttributes(mark, length, style, false);
                

            } 
      catch (BadLocationException e) {
                e.printStackTrace();
            }
       
      
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       String s1 = ta1.getText();
        
        int mark = ta1.getCaret().getMark();
        int dot = ta1.getCaret().getDot();
       
       StyledDocument style_obj = (StyledDocument) ta1.getDocument();
       
      try {
                int length = dot - mark;
                String s = style_obj.getText(mark, length);
                
                //style_obj.remove(mark, length);
                
                //style_obj.insertString(mark, s,
                        //style_obj.getStyle("bold"));
                
                Style style = style_obj.addStyle("Italic", null);
                
                StyleConstants.setItalic(style, false);
                StyleConstants.setBold(style, false);
                StyleConstants.setUnderline(style, false);

                
                style_obj.setCharacterAttributes(mark, length, style, false);
                

            } 
      catch (BadLocationException e) {
                e.printStackTrace();
            }
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      String s1 = ta1.getText();
        
        int mark = ta1.getCaret().getMark();
        int dot = ta1.getCaret().getDot();
       
       StyledDocument style_obj = (StyledDocument) ta1.getDocument();
       
      try {
                int length = dot - mark;
                String s = style_obj.getText(mark, length);
                
                //style_obj.remove(mark, length);
                
                //style_obj.insertString(mark, s,
                        //style_obj.getStyle("bold"));
                
                Style style = style_obj.addStyle("Italic", null);
                StyleConstants.setUnderline(style, true);
                
                style_obj.setCharacterAttributes(mark, length, style, false);
                

            } 
      catch (BadLocationException e) {
                e.printStackTrace();
            }
       
      
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btn_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gActionPerformed
        try
        {
            String url = "https://www.google.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            btn2.setEnabled(true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_gActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         try
        {
            String url = "https://www.epicurious.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            btn2.setEnabled(true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
 try
        {
            String url = "https://www.foodnetwork.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            btn2.setEnabled(true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
            
            
        }    }//GEN-LAST:event_btn_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
        
         try {
            String msgin = "";
            
            s = new Socket("127.0.0.1",1201); // ip address is of localhost because server is running on the same mschine
            dis = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            while (!msgin.equals("exit")) {
                msgin = dis.readUTF();
                msg_area.setText(msg_area.getText() + "\n Researcher : " + msgin);
            }

        } catch (Exception e) {
            //handle the exception here
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Task1;
    public javax.swing.JFrame Task2;
    private javax.swing.JFrame Task3;
    private javax.swing.JTextField bp;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_g;
    private javax.swing.JButton btn_nextPass;
    private javax.swing.JTextField bu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JTextField msg_text;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField pu;
    private javax.swing.JTextField sp;
    private javax.swing.JTextField su;
    private javax.swing.JTextPane ta1;
    private javax.swing.JTextArea ta10;
    private javax.swing.JTextArea ta3;
    private javax.swing.JTextArea ta4;
    private javax.swing.JTextArea ta5;
    private javax.swing.JTextArea ta6;
    private javax.swing.JFrame task10;
    private javax.swing.JFrame task4;
    private javax.swing.JFrame task5;
    private javax.swing.JFrame task6;
    private javax.swing.JFrame task7;
    private javax.swing.JFrame task8;
    private javax.swing.JFrame task_8;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JLabel txt_gen_pass;
    private javax.swing.JTextField up;
    private javax.swing.JTextField uu;
    private javax.swing.JTextField wp;
    private javax.swing.JTextField wu;
    // End of variables declaration//GEN-END:variables
}
